ENH: Allow `DatasetMetadataExtractor.get_required_content()` to yield a generator
datalad/datalad-metalad pull request #361
Opened 2023-03-02 13:09 UTC by jsheunis

This PR:
- Adds logic to `extract.py` to allow either a returned `bool` or a yielded`Generator` to be interpreted correctly: If an extractor implements logic where any result record is yielded with a failure 'status' (i.e. equal to 'impossible' or 'error') the extractor infrastructure will signal an error and the extractor's extract method will not be called.
- Updates the docstring of `DatasetMetadataExtractor.get_required_content()` in `extractors/base.by` to indicate this change, especially to developers implementing extractors 
- Adds missing `return` statements in `extract.py` where failures are yielded
- Updates related documentation
- Closes https://github.com/datalad/datalad-metalad/issues/356

2023-03-02 15:02 UTC, christian-monch requested changes
Nice, thanks a lot. A few comments below

2023-03-02 15:02 UTC, christian-monch commented on docs/source/user_guide/writing-extractors.rst
> +              failure_count+=1
```suggestion
              failure_count += 1
```

2023-03-02 15:39 UTC, jsheunis commented on datalad_metalad/extractors/base.py
> +    def get_required_content(self) -> Union[bool, Generator]:
Might be moot depending on https://github.com/datalad/datalad-metalad/pull/361#discussion_r1123301625

2023-03-02 15:39 UTC, jsheunis commented on datalad_metalad/extractors/base.py
> +        (True/False) value OR yield DataLad result records.
Might be moot depending on https://github.com/datalad/datalad-metalad/pull/361#discussion_r1123301625

2023-03-02 15:40 UTC, jsheunis commented on docs/source/user_guide/writing-extractors.rst
> +The function should either return a boolean value (``True | False``) or yield a ``Generator`` with
See comment https://github.com/datalad/datalad-metalad/pull/361#discussion_r1123301625

2023-03-03 08:14 UTC, christian-monch commented on datalad_metalad/extract.py
> +    if isinstance(res, bool) or res is None:
> Is this intentional to not return a boolean in this part of the test? If not, we can just add a return True, and remove all references to None in the existing commits of this PR.

No, that is not intentional, let's add ``return True`` and remove all ``None`` references.

2023-03-03 08:15 UTC, christian-monch commented on datalad_metalad/extractors/base.py
> +    def get_required_content(self) -> Union[bool, Generator]:
We leave it as is and require return of ``Union[bool, Generator]``

2023-03-03 08:17 UTC, christian-monch commented on docs/source/user_guide/writing-extractors.rst
> +The function should either return a boolean value (``True | False``) or yield a ``Generator`` with
We leave None out. But the function does not "yield" a generator, it "returns" a generator.
```suggestion
The function should either return a boolean value (``True | False``) or return a ``Generator`` with 
```

2023-03-03 08:23 UTC, christian-monch commented on datalad_metalad/extractors/base.py
> +        (True/False) value OR yield DataLad result records.
It's fine

2023-03-03 09:32 UTC, jsheunis commented on docs/source/user_guide/writing-extractors.rst
> +The function should either return a boolean value (``True | False``) or yield a ``Generator`` with
Updated in [58c51e5](https://github.com/datalad/datalad-metalad/pull/361/commits/58c51e5de8abeb7df66cbf569ce838384e207708)

2023-03-03 09:32 UTC, jsheunis commented on datalad_metalad/extract.py
> +    if isinstance(res, bool) or res is None:
Done in [58c51e5](https://github.com/datalad/datalad-metalad/pull/361/commits/58c51e5de8abeb7df66cbf569ce838384e207708)

2023-03-03 13:59 UTC, christian-monch approved these changes
LGTM, thanks @jsheunis

2023-03-03 15:04 UTC, jsheunis commented
Great! @christian-monch feel free to merge if you're happy.

2023-03-07 10:13 UTC, merged