MNT: Refactor extraction code
datalad/datalad-metalad pull request #367
Opened 2023-03-16 20:27 UTC by jsheunis

This PR:
- moves the `get_required_content` method to the base class `MetadataExtractorBase` so that both `FileMetadataExtractor` and `DatasetMetadataExtractor` can make use of it (addresses https://github.com/datalad/datalad-metalad/issues/287)
- refactors `extract.py` in order to deduplicate code, and updates related tests (addresses https://github.com/datalad/datalad-metalad/issues/366):
   - merges `do_file_extraction()` and `do_dataset_extraction()` into a single function `do_extraction()`, with a new argument `extractor_type`, which would be either `'file'` or `'dataset'`.
   - merges `perform_file_metadata_extraction()` and `perform_dataset_metadata_extraction()` into a single function `perform_metadata_extraction()`

2023-03-16 21:18 UTC, christian-monch requested changes
Thx @jsheunis .

Only one thing. Let's move the ``extractor_type`` variable into the ``ExtractionArguments``-class (see comments in the code)

2023-03-16 21:18 UTC, christian-monch commented on datalad_metalad/extract.py
> +        yield from do_extraction(ep=extraction_arguments, extractor_type=extractor_type)
```suggestion
            extractor_type = 'dataset'
        
        yield from do_extraction(ep=extraction_arguments)
```
(add extractor_type to ExtractionArguments)

2023-03-16 21:18 UTC, christian-monch commented on datalad_metalad/extract.py
> +def do_extraction(ep: ExtractionArguments, extractor_type: str):
```suggestion
def do_extraction(ep: ExtractionArguments):
    extractor_type = ep.extractor_type    
```

(add extractor_type to ExtractionArguments)

2023-03-16 21:18 UTC, christian-monch commented on datalad_metalad/extract.py
> +            ep.source_dataset.path / ep.file_tree_path \
```suggestion
            ep.source_dataset.path / ep.file_tree_path
```

The continuation is not required

2023-03-16 21:47 UTC, jsheunis commented
Thanks, good suggestion. I committed some of your suggestions, added more changes in [9eb3a51](https://github.com/datalad/datalad-metalad/pull/367/commits/9eb3a517a2c2542f9cf1d85fef16d19b7b1f5750), including updating tests to reflect the changed parameter.

2023-03-16 21:50 UTC, jsheunis commented
@christian-monch I'll leave the merging to you once you're happy with the state of the PR.

2023-03-17 08:36 UTC, merged

2023-03-17 08:36 UTC, christian-monch commented
Thx a lot @jsheunis